// File generated by properties_gen (2018-07-29 22:48:46)
extern struct property * p_sound[10];
extern struct property * p_playback[11];
extern struct property * p_gui_misc[6];
extern struct property * p_network[7];
